import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Verify Envionment Variables
import "../types/env";
import { getServerSession } from "next-auth";
import { nextAuthOptions } from "./(apis)/api/auth/[...nextauth]/authOptions";
import Providers from "@/components/contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions);

  return (
    <html lang="en">
      <Providers session={session}>
        <body className={`${inter.className} dark`}>{children}</body>
      </Providers>
    </html>
  );
}
